//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcBPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contact()
        {
            this.project = new HashSet<project>();
        }
    
        public string id { get; set; }
        public string staff_id { get; set; }
        public string contact_no { get; set; }
        public string contact_name { get; set; }
        public decimal contact_amount { get; set; }
        public System.DateTime contact_signing_data { get; set; }
        public long contact_deadline { get; set; }
        public string delegation_client { get; set; }
        public string dlg_contactperson { get; set; }
        public string dlg_contactperson_phone { get; set; }
        public string accept_way { get; set; }
        public bool is_corporation_signed { get; set; }
        public bool is_client_signed { get; set; }
    
        public virtual staff staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> project { get; set; }
    }
}
