//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcBPMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPMSxEntities : DbContext
    {
        public BPMSxEntities()
            : base("name=BPMSxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<prj_complex_coff> prj_complex_coff { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<project_diffcult_coff> project_diffcult_coff { get; set; }
        public virtual DbSet<project_fund__allocation> project_fund__allocation { get; set; }
        public virtual DbSet<project_money_flow> project_money_flow { get; set; }
        public virtual DbSet<project_system> project_system { get; set; }
        public virtual DbSet<r_project_staff> r_project_staff { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
