//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcBPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_fund__allocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_fund__allocation()
        {
            this.project_system = new HashSet<project_system>();
        }
    
        public string id { get; set; }
        public string prj_allocation_type { get; set; }
        public Nullable<double> scene { get; set; }
        public Nullable<double> plan { get; set; }
        public Nullable<double> report { get; set; }
        public Nullable<double> check { get; set; }
        public Nullable<double> others { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_system> project_system { get; set; }
    }
}
