//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcBPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_system
    {
        public string id { get; set; }
        public string project_fund__allocation_id { get; set; }
        public string prj_complex_coff_id { get; set; }
        public string project_id { get; set; }
        public string project_diffcult_coff_id { get; set; }
    
        public virtual prj_complex_coff prj_complex_coff { get; set; }
        public virtual project project { get; set; }
        public virtual project_diffcult_coff project_diffcult_coff { get; set; }
        public virtual project_fund__allocation project_fund__allocation { get; set; }
    }
}
