//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcBPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_money_flow
    {
        public string id { get; set; }
        public string staff_id { get; set; }
        public string project_id { get; set; }
        public System.DateTime fund_flow_datetime { get; set; }
        public decimal expense { get; set; }
        public decimal invoice_amount { get; set; }
        public Nullable<decimal> income_amout { get; set; }
    
        public virtual project project { get; set; }
        public virtual staff staff { get; set; }
    }
}
