//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcBPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_project_staff
    {
        public string id { get; set; }
        public string project_id { get; set; }
        public string staff_id { get; set; }
        public bool is_scene { get; set; }
        public bool is_scheme { get; set; }
        public bool is_report { get; set; }
    
        public virtual project project { get; set; }
        public virtual staff staff { get; set; }
    }
}
